### DISCUSSION TITLE
Surprise Test - React

### DISCUSSION THREAD

**Discussion by akash-coded** [akash-coded/mern#107] [Tasks]
1. Build Search filter in React
React code to build a simple search filter functionality to display a filtered list based on the search query entered by the user.

    The following are the steps to create a Search filter using React JS:

    1. Declare React states for search input values.
    2. Create HTML input text for entering search term and update state in onChange function.
    3. Add Array.filter() on list of items with search term value.

    ![image](https://user-images.githubusercontent.com/60097560/190854939-a211af7d-d85c-4455-884f-d449e3349514.png)

2. Build Accordion in React
Creating an accordion that toggles text content on click of the accordion header using React State and conditional rendering.

    The following are the steps to create an accordion in React JS:

    1. Display every title of accordion with body.
    2. Hide every accordion body using element.display = none;
    3. Toggle visibility of accordion body on click of title.

    ![image](https://user-images.githubusercontent.com/60097560/190855045-6a37cb47-9eba-48a9-9558-109aa330597a.png)

3. Image Slider using React JS
React exercise to create an image slide, where users can view multiple images with next/previous buttons. Additionally, there is also an option to select an image from any index of the list through a click-on option circle.

    The following are the steps to create an image slider in React JS:
    1. Declare array of objects with id and image URL.
    2. For pre/next functionality, we decrement/increment count of the index of active image.
    3. Update active image index with clicked option.
    
    ![image](https://user-images.githubusercontent.com/60097560/190855244-8ef2dc74-42ec-4b85-8dd4-fe05dc5094c0.png)

5. Simple Login form in React
React code for simple login form where the user login by entering their username and password. The form inputs are validated to check if correct information is entered and the error messages are the validation fails. The login form is hidden and the “Welcome, ${name}” message is shown when the user login is successful.

    The following are the steps to create a simple login form using React JS:

    1. Create name, email and password input form elements.
    2. React States to store user input values.
    3. Add form validation for compare name, email and password with correct values.
    4. Display “Welcome, ${name}” if login is successful, else display the error message.

**Comment by shubhamk-coder** [comment]
## Question-1 
### fruits.json
```json
[
{"name" : "Banana"},
{"name" : "Apple"},
{"name" : "Orange"},
{"name" : "Mango"},
{"name" : "Pineapple"},
{"name" : "Watermelon"}
]
```
### App.js
```javascript
import React, { useState } from "react";
import "./App.css";
import FRUITS from "./fruits.json";

function App() {
  const [searchTerm, setSearchTerm] = useState("");
  return (
    <div className="App">
      <label for="search">Search: </label>
      <input
        type="text"
        id="search"
        name="search"
        placeholder="search"
        onChange={(event) => {
          setSearchTerm(event.target.value);
        }}
      />
      {FRUITS.filter((val) => {
        if (searchTerm == "") {
          return val;
        } else if (val.name.toLowerCase().includes(searchTerm.toLowerCase())) {
          return val;
        }
      }).map((val, key) => {
        return (
          <div>
            <p>{val.name}</p>
          </div>
        );
      })}
    </div>
  );
}

export default App;
```
### Screenshots
![image](https://user-images.githubusercontent.com/36131539/190857827-df33ffb5-9690-4f43-8ebe-929df35a8bac.png)
![image](https://user-images.githubusercontent.com/36131539/190857840-a9e08439-903a-4624-b13d-3d44772565b1.png)
![image](https://user-images.githubusercontent.com/36131539/190857866-e63b127b-adce-48b0-8256-247a6dfda1a1.png)
## Question-2
### App.js
```javascript
import React from "react";
import Accordion from "./components/Accordion";
import { Data } from "./components/Data";

const App = () => {
  return (
    <div>
      <div className="accordion">
        {Data.map(({ title, content }) => (
          <Accordion title={title} content={content} />
        ))}
      </div>
    </div>
  );
};

export default App;
```
### Data.js
```javascript
export const Data = [
  {
    title: "What is your return policy?",
    content: `you may return undamaged items 30 days after purchase for a full refund of your purchase`,
  },
  {
    title: "How do I track my order?",
    content: `Lorem ipsum, dolor sit amet consectetur adipisicing elit.`,
  },
  {
    title: "Can I purchase items again?",
    content: `Lorem ipsum, dolor sit amet consectetur adipisicing elit.`,
  },
];
```
### Accordion.js
```javascript
import React, { useState } from "react";

const Accordion = ({ title, content }) => {
  const [isActive, setIsActive] = useState(false);

  return (
    <div className="accordion-item">
      <div className="accordion-title" onClick={() => setIsActive(!isActive)}>
        <div>{title}</div>
        <div>{isActive ? "-" : "+"}</div>
      </div>
      {isActive && <div className="accordion-content">{content}</div>}
    </div>
  );
};

export default Accordion;
```
### styles.css
```css
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }
  
  body {
    font-family: Verdana, Geneva, Tahoma, sans-serif;
    font-size: 20px;
    background: #fff;
  }
  
  .accordion {
    max-width: 600px;
    margin: 2rem auto;
    margin-top: 100px;
    box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;
  }
  
  .accordion-title {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    cursor: pointer;
    background-color: #DCDCDC;
  }
  
  .accordion-title:hover {
    background-color: #A9A9A9;
  }
  
  .accordion-title,
  .accordion-content {
    padding: 1rem;
  }
  
  .accordion-content {
    background-color: #FFFFFF;
  }
  
  @media screen and (max-width: 700px) {
    body {
      font-size: 18px;
    }
  
    .accordion {
      width: 90%;
    }
  }
```
### Screenshots
![image](https://user-images.githubusercontent.com/36131539/190859488-020f4c41-e17b-4a0f-aaba-9d3dee9202a2.png)
![image](https://user-images.githubusercontent.com/36131539/190859523-be22b740-c28f-471a-a30f-2e2a4b8ad197.png)
![image](https://user-images.githubusercontent.com/36131539/190859554-c7e8da44-085b-4bec-b440-fad3e272ce5b.png)
## Question-3
### App.js
```javascript
import "./App.css";
import Slider from "./components/Slider";

function App() {
  return (
    <>
      <Slider />
    </>
  );
}

export default App;
```
### App.css
```css
*, ::before, ::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: Open sans, sans-serif;
  height: 100vh;
  background: #f1f1f1;
  overflow: hidden;
}
```
### Slider.js
```javascript
import React, { useState } from "react";
import "./slider.css";
import BtnSlider from "./Btn";
import dataSlider from "./Data";

export default function Slider() {
  const [slideIndex, setSlideIndex] = useState(1);

  const nextSlide = () => {
    if (slideIndex !== dataSlider.length) {
      setSlideIndex(slideIndex + 1);
    } else if (slideIndex === dataSlider.length) {
      setSlideIndex(1);
    }
  };

  const prevSlide = () => {
    if (slideIndex !== 1) {
      setSlideIndex(slideIndex - 1);
    } else if (slideIndex === 1) {
      setSlideIndex(dataSlider.length);
    }
  };

  const moveDot = (index) => {
    setSlideIndex(index);
  };

  return (
    <div className="container-slider">
      {dataSlider.map((obj, index) => {
        return (
          <div
            key={obj.id}
            className={slideIndex === index + 1 ? "slide active-anim" : "slide"}
          >
            <div className="title">
              <p>{obj.title}</p>
            </div>
            <div className="subtitle">
              <p>{obj.subTitle}</p>
            </div>
            <img src={process.env.PUBLIC_URL + `/Imgs/img${index + 1}.jpg`} />
          </div>
        );
      })}
      <BtnSlider moveSlide={nextSlide} direction={"next"} />
      <BtnSlider moveSlide={prevSlide} direction={"prev"} />

      <div className="container-dots">
        {Array.from({ length: 5 }).map((item, index) => (
          <div
            onClick={() => moveDot(index + 1)}
            className={slideIndex === index + 1 ? "dot active" : "dot"}
          ></div>
        ))}
      </div>
    </div>
  );
}
```
### slider.css
```css
.container-slider {
    max-width: 700px;
    height: 500px;
    margin: 50px auto 0;
    position: relative;
    overflow: hidden;
    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
  }
  @media screen and (max-width: 700px){
    .container-slider {
      margin: 100px 10px 0;
    }
  }
  .slide {
    width: 100%;
    height: 100%;
    position: absolute;
    opacity: 0;
    transition: opacity ease-in-out 0.4s;
  }
  .slide img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
  .active-anim {
    opacity: 1;
  }
  
  .btn-slide {
    width: 60px;
    height: 60px;
    border-radius: 50%;
    background: #f1f1f1;
    border: 1px solid rgba(34, 34, 34, 0.287);
    position: absolute;
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
  }
  
  .btn-slide img {
    width: 25px;
    height: 25px;
    pointer-events: none;
  }
  .prev {
    top: 50%;
    left: 20px;
    transform: translateY(-60%);
  }
  .next {
    top: 50%;
    right: 20px;
    transform: translateY(-60%);
  }
  .title {
    position: absolute;
    width: auto;
    height: 40px;
    color: #fff;
    font-size: 30px;
    bottom: 80px;
    left: 50%;
    transform: translateX(-50%);
    display: flex;
  }

  .subtitle {
    position: absolute;
    width: auto;
    height: 40px;
    color: #fff;
    font-size: 30px;
    bottom: 40px;
    left: 50%;
    transform: translateX(-50%);
    display: flex;
  }
  
  .container-dots {
    position: absolute;
    bottom: 10px;
    left: 50%;
    transform: translateX(-50%);
    display: flex;
  }
  .dot {
    width: 40px;
    height: 4px;
    margin: 0 5px;
    background: #f1f1f1;
  }
  .dot.active {
    background: rgb(32, 32, 32);
  }
```
### Btn.js
```javascript
import React from "react";
import "./slider.css";
import leftArrow from "./icons/left-arrow.svg";
import rightArrow from "./icons/right-arrow.svg";

export default function Btn({ direction, moveSlide }) {
  console.log(direction, moveSlide);
  return (
    <button
      onClick={moveSlide}
      className={direction === "next" ? "btn-slide next" : "btn-slide prev"}
    >
      <img src={direction === "next" ? rightArrow : leftArrow} />
    </button>
  );
}
```
### Data.js
```javascript
const Data = [
  {
    id: 1,
    title: "Lorem ipsum 1",
    subTitle: "Lorem 1",
  },
  {
    id: 2,
    title: "Lorem ipsum 2",
    subTitle: "Lorem 2",
  },
  {
    id: 3,
    title: "Lorem ipsum 3",
    subTitle: "Lorem 3",
  },
  {
    id: 4,
    title: "Lorem ipsum 4",
    subTitle: "Lorem 4",
  },
  {
    id: 5,
    title: "Lorem ipsum 5",
    subTitle: "Lorem 5",
  },
];

export default Data;
```
### Screenshots
![image](https://user-images.githubusercontent.com/36131539/190862416-22978e9c-7fe5-4374-bc60-c19f97f00acc.png)
![image](https://user-images.githubusercontent.com/36131539/190862449-8841ddac-9060-4a9f-93bf-bf7920fa8d83.png)
![image](https://user-images.githubusercontent.com/36131539/190862457-727c76e3-0e1f-4f99-8168-485870ea9a7a.png)
![image](https://user-images.githubusercontent.com/36131539/190862467-d832f030-318e-41e5-b238-d555750f2391.png)
![image](https://user-images.githubusercontent.com/36131539/190862475-5e48479f-0c7a-4f01-83c7-c5674442edd2.png)
## Question-4
### App.js
```javascript
import React, { useState } from "react";
import LoginForm from "./components/LoginForm";

function App() {
  const adminUser = {
    email: "admin@admin.com",
    password: "admin123",
  };

  const [user, setUser] = useState({ name: "", email: "" });
  const [error, setError] = useState("");

  function Login(details) {
    console.log(details);

    if (
      details.email == adminUser.email &&
      details.password == adminUser.password
    ) {
      console.log("Logged In");
      setUser({
        name: details.name,
        email: details.email,
      });
    } else {
      console.log("Details do not Match!");
      setError("Details do not Match!");
    }
  }

  const Logout = () => {
    setUser({ name: "", email: "" });
  };
  return (
    <div className="App">
      {user.email != "" ? (
        <div className="welcome">
          <h2>
            Welcome, <span>{user.name}</span>
          </h2>
          <button onClick={Logout}>Logout</button>
        </div>
      ) : (
        <LoginForm LOGIN={Login} error={error} />
      )}
    </div>
  );
}

export default App;
```
### LoginForm.js
```javascript
import React, { useState } from "react";

function LoginForm({ Login, error }) {
  const [details, setDetails] = useState({ name: "", email: "", password: "" });

  const submitHandler = (e) => {
    e.preventDefault();
    Login(details);
  };

  return (
    <form onSubmit={submitHandler}>
      <div className="form-inner">
        <h2>Login</h2>
        {error != "" ? <div className="error"></div> : ""}
        <div className="form-group">
          <label htmlFor="name">Name:</label>
          <input
            type="text"
            name="name"
            id="name"
            onChange={(e) => setDetails({ ...details, name: e.target.value })}
            value={details.name}
          />
        </div>
        <div className="form-group">
          <label htmlFor="email">Email:</label>
          <input
            type="email"
            name="email"
            id="email"
            onChange={(e) => setDetails({ ...details, email: e.target.value })}
            value={details.email}
          />
        </div>
        <div className="form-group">
          <label htmlFor="password">Password:</label>
          <input
            type="password"
            name="password"
            id="password"
            onChange={(e) =>
              setDetails({ ...details, password: e.target.value })
            }
            value={details.password}
          />
        </div>
        <input type="submit" value="LOGIN" />
      </div>
    </form>
  );
}

export default LoginForm;
```
### index.css
```css
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: montserrat, sans-serif;
}

input, button {
  appearance: none;
  background: none;
  border: none;
  outline: none;
}

.App {
  height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #535353;
}

form {
  display: block;
  position: relative;
}

form:after {
  content: '';
  display: block;
  position: absolute;
  top: -5px;
  left: -5px;
  right: -5px;
  bottom: -5px;
  z-index: 1;
  background-image: linear-gradient(to right, #fc466b, #3f5efb);
}

form .form-inner {
  position: relative;
  display: block;
  background-color: #fff;
  padding: 30px;
  z-index: 2;
}

form .form-inner h2 {
  color: #888;
  font-size: 28px;
  font-weight: 500;
  margin-bottom: 30px;
}

form .form-inner .form-group {
  display: block;
  width: 300px;
  margin-bottom: 15px;
}

.form-inner .form-group label {
  display: block;
  color: #666;
  font-size: 12px;
  margin-bottom: 5px;
  transition: 0.4s;
}

.form-inner .form-group:focus-within label {
  color: #fe4880;
}

form .form-inner .form-group input {
  display: block;
  width: 100%;
  padding: 10px 15px;
  background-color: #F0F0F0;
  border-radius: 8px;
  transition: 0.4s;
}

form .form-inner .form-group input:focus {
  box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.2);
}

form .form-inner input[type="submit"], .welcome button {
  display: inline-block;
  padding: 10px 15px;
  border-radius: 8px;
  background-image: linear-gradient(to right, #fc466b, #3f5efb);
  background-size: 200%;
  background-position: 0%;
  transition: 0.4s;
  color: #fff;
  font-weight: 700;
  cursor: pointer;
}

form .form-inner input[type="submit"]:hover, .welcome button:hover {
  background-position: 100% 0%;
}

.welcome {
  width: 100%;
  max-width: 480px;
  background-color: #fff;
  padding: 15px 30px;
}

.welcome h2 {
  color: #888;
  font-size: 28px;
  font-weight: 500;
  margin-bottom: 30px;
}

.welcome h2 span {
  color: #FE4880;
  font-weight: 700;
}
```
### Screeenshots
![image](https://user-images.githubusercontent.com/36131539/190871519-6d6b9777-fa66-40d5-bb8f-f421120fbf0d.png)

**Comment by Amrita-12345** [comment]
## Q.1
```js
import { useState } from "react"

const fruits = [
  "Banana",
  "Apple",
  "Orange",
  "Mango",
  "Pineapple",
  "Watermelon",
]
function App() {
  const [searchValue, setSearchValue] = useState("")
 return (
     <div className="container">
    <div className="App">
      <h1>Search filter</h1>
      <input
        type="text"
        name="search"
        value={searchValue}
        onChange={event => setSearchValue(event.target.value)}
      />
      <ul>
        {fruits
          .filter(name => name.match(new RegExp(searchValue, "i")))
          .map(name => {
            return <li key={name}>{name} </li>
          })}
      </ul>
    </div>
    </div>
  )
}
export default App
```
### Screenshot
![image](https://user-images.githubusercontent.com/104146616/190858921-a8d085a1-8159-4024-8996-73ab556f8acc.png)
![image](https://user-images.githubusercontent.com/104146616/190858964-11775818-fab7-48ac-8030-2d1eae8eb6bb.png)
![image](https://user-images.githubusercontent.com/104146616/190858972-61e7980b-060a-4cf2-89c7-f3364157d09f.png)

**Comment by Nimje1998** [comment]
import React, { useState } from "react";

import "./styles.css";

function App() {

  const list = [
    "Banana",
    "Apple",
    "Orange",
    "Mango",
    "Pineapple",
    "Watermelon"
  ];

  const [filterList, setFilterList] = useState(list);

  const handleSearch = (event) => {

    if (event.target.value === "") {
setFilterList(list);
      return;
    }

    const filteredValues = list.filter(
      (item) =>
        item.toLowerCase().indexOf(event.target.value.toLowerCase()) !== -1
    );
    setFilterList(filteredValues);
  };
  return (
    <div className="app">
      <div>
        Search: <input name="query" type="text" onChange={handleSearch} />
      </div>
      {filterList &&
        filterList.map((item, index) => (
          <div key={index}>{item}</div> //Display each item
        ))}
    </div>
  );
}

export default App;


Style.CSS

.app {
  font-family: sans-serif;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  gap: 20px;
  height: 100vh;
  font-family: Cambria, Cochin, Georgia, Times, "Times New Roman", serif;
}

**Comment by SumaGayathri-999** [comment]
### CODE

### QN 1
```javascript
import React,{useState} from 'react'
 
function SearchItems(){
    const[filterText,setfilterText]=useState("");
    const arr=['Banana','Apple','Orange','Mango','Pinapple','Watermelon']
    return(
        <center>
            <Search filterText={filterText} onTextChange={setfilterText}/>
            <Filteredlist arr={arr} filterText={filterText} />
        </center>
    )
}
function Search({filterText,onTextChange}){
      return(
        <div>
            <label>Search:</label>
            <input type='search' value={filterText} onChange={(e)=>onTextChange(e.target.value) } />
        </div>
      )
}
function Filteredlist({arr,filterText}){
    
    const filtered=arr.filter(
        (text)=>{
            if(text.toLowerCase().includes(filterText.toLowerCase()))
                   {
                    return text;
                   }
        }

    )
    const filtered_array=filtered.map((element)=><div><p>{element}</p></div>);
    return(
        <center>
            {filtered_array }
        </center>
    )
}

export default SearchItems;
```
### SCREENSHOTS
![image](https://user-images.githubusercontent.com/104271789/190861641-cacb202b-f90c-4caa-8799-a0a176e1ec47.png)


![image](https://user-images.githubusercontent.com/104271789/190861693-a4e7a944-29b3-4db7-97ff-fe2bec273157.png)

### QN 2

### CODE
**Accordion.js**
```javascript
import React,{ useState} from 'react';
import '../cssFolder/Accordion.css';

function Accordion(){
   
    const data_obj=[
        {
        header:"What is my return policy",
        content:"You may return undamaged items 30 days after purchase for a full refund of your product"
        },
        {
        header:"How do I track my order",
        content:"you can track the order in the my orders page"
        },
        {
        header:"Can I purchase items again",
        content:"Yes you can purchase item again"
        }
    ];
    return(
        <div className="card">
            {
              data_obj.map((data)=><Structure data={data} />)
            }
        </div>
    )
}
function Structure({data}){
    const [choice,setChoice]=useState(false);
     return(
        <div className="Accordion_card">
                <div className="Accordion_title" onClick={()=>setChoice(!choice)}>
                    <div>{data.header}</div>
                    {choice ? <div>-</div> : <div>+</div>}
                </div >
                {choice ? <div className="Accordion_content">{data.content}</div> :""}
        </div>
     )
}
export default Accordion;
```
**Accordion.css**
```css
*{
    margin:0;
    padding:0;
    box-sizing: border-box;
}
body{
    background-color:aliceblue;
    display:flex;
    align-items:center; 
    height:calc(100vh - 1px);
    justify-content: center;
}
.card{
    box-shadow:0px 0px 10px grey;
    width:600px;
}
.Accordion_card{
    background-color: white;
}
.Accordion_title{
    background-color:rgb(219, 218, 218);
    padding:10px;
    display:flex;
    flex-direction:row;
    cursor:pointer;
    justify-content: space-between;
}
.Accordion_title:hover{
    background-color:rgb(92, 90, 90);
}
.Accordion_content{
    padding:10px;
}
```
### SCREENSHOT 1
![image](https://user-images.githubusercontent.com/104271789/190956397-a21f4db8-3418-4579-b032-d0050704dce2.png)
### SCREENSHOT 2
![image](https://user-images.githubusercontent.com/104271789/190956873-02a2369e-4e5d-4634-880f-aad987f5cdb6.png)

### QN 3
### Corousal.js
```javascript
import React,{ useState,useEffect } from 'react';
import '../cssFolder/corousal.css'

function Corousal(){
    const[slide,setSlide]=useState(0);

    useEffect(()=>{
        const Interval=setInterval(()=>{moveRight();},10000);
        return ()=>{clearInterval(Interval);

       }

    },[slide])
    const images_array=[
        {
            id:1,
            url:"assets/lake.jpg",
            title:"Lake image",
            content:"This is Lake image"
        },
        {
            id:2,
            url:"assets/landscape.jpg",
            title:"Landscape",
            content:"This is Landscape image"
        },
        {
            id:3,
            url:"assets/sunrise.jpg",
            title:"Sunrise",
            content:"This is Sunrise image"
        }
    ]
    function moveRight(){
        slide !== images_array.length-1 ? setSlide(slide+1) : setSlide(0);
    }
    function moveLeft(){
        slide !== 0 ? setSlide(slide-1) : setSlide(images_array.length-1)
    }
    return(
     <div key={slide} className="corousal" >
        <button className="prev arrow_button"  onClick={moveLeft}>&lt;</button>
            <img  className="slide_image tech" src={images_array[slide].url} alt=" " /> 
            <h1>{images_array[slide].title}</h1>
            <p>{images_array[slide].content}</p>
         <button className="next arrow_button "  onClick={moveRight}>&gt;</button>
         <div className="navigation_buttons">
            {images_array.map((image,index)=><div><button className="nav_button" onClick={()=>setSlide(index)}></button></div>)}
         </div>
    </div>
    )
}
export default Corousal;
```
### corousal.css
```css
*{
    margin:0;
    padding: 0;
    box-sizing: border-box;
}
body{
    background-color:aliceblue;
    display:flex;
    align-items:center; 
    height:calc(100vh - 1px);
    justify-content: center;
}
.corousal{
    width:600px;
    height:400px;
    position:relative;
    box-shadow: 0px 0px 10px 5px grey;
    animation-name:sliding;
    animation-duration: 4s;
}
@keyframes sliding{
    from {opacity:0;}
    to {opacity:1;}
}
.slide_image{
   width: 100%;
   height: 100%;
   position:absolute;
   top:0;
   bottom:0;
   object-fit: cover;
}
.arrow_button{
    position:absolute;
    z-index: 1;
    cursor:pointer;
    width:50px;
    height:50px;
    border-radius:50%;
    border-coloR:grey;
    font-size:25px;
}
.prev{
    left: 5%;
    top:50%;
    transform:translateY(-50%);
}
.next{
    right: 5%;
    top:50%;
    transform:translateY(-50%);
}
h1{
    position:absolute;
    bottom:50px;
    display:flex;
    left:50%;
    transform: translateX(-50%);
}
p{
    position:absolute;
    bottom:30px;
    left:50%;
    transform: translateX(-50%);
    color:white;
    font-size: 20px;
}
.nav_button{
    width:50px;
    height:6px;
     margin:0 10px;
     justify-content: space-between;
     cursor:pointer;
     opacity:0.5;
}
.nav_button:hover{
    border:none;
    border-radius:1.5rem;
    background-color:black;
}
.navigation_buttons{
    bottom:10px;
    position:absolute;
    display:flex;
    justify-content: space-between;
    left:50%;
    transform: translateX(-50%);
}
```

### SCREENSHOT 1
![image](https://user-images.githubusercontent.com/104271789/191483981-1a380885-e748-400a-8b96-a13803970009.png)
### SCREENSHOT 2
![image](https://user-images.githubusercontent.com/104271789/191485143-a8ac7f7e-f3d5-42ec-b498-d181799f935b.png)
### SCREENSHOT 3
![image](https://user-images.githubusercontent.com/104271789/191484858-78a34322-9b13-46de-97e3-03ceab76bd3f.png)

### QN 4
### LoginForm.js
```javascript
import React,{ useState } from 'react';
import '../cssFolder/LoginForm.css'

function LoginForm()
{
    const [name,setName]=useState("");
    const [email,setEmail]=useState("");
    const [password,setPassword]=useState("");
    const [formvalid,setFormvalid]=useState(false);
    const [showError,setShowError]=useState(false)
   
    function changeName(username)
    {
        setName(username)
    }
    function changeEmail(useremail)
    {
        setEmail(useremail)
    }
    function changePassword(userpassword)
    {
        setPassword(userpassword)
    }
    function submitHandler(event){
        event.preventDefault();
        console.log("hello");
        setFormvalid(email.includes("@") && password.trim().length > 6);
        setShowError(true);
    }
    return (
        <div className="card">
            {!formvalid ? <form >
                {showError && <p className="errormessage">Error</p>}
                <label>Name:
                    <input type="text" value={name} onChange={(e)=>changeName(e.target.value)}></input><br />
                </label>
                <label>Email:
                <input type="email" value={email} onChange={(e)=>changeEmail(e.target.value)}></input><br />
                </label>
                <label>Password:
                <input type="password" value={password} onChange={(e)=>changePassword(e.target.value)}></input><br/>
                </label>
                <button className="loginbutton" onClick={submitHandler}>Login</button>
            </form> 
                       : <Homepage username={name} />}
        </div>
    )
}
function Homepage({username})
{
     return (
        <div>
            <h1>Welcome {username} !</h1>
        </div>
     )
}
export default LoginForm;
```
### LoginForm.css

```css
*{
    margin:0;
    padding: 0;
    box-sizing: border-box;
}
body{
    background-color:aliceblue;
    display:flex;
    align-items:center; 
    height:calc(100vh - 1px);
    justify-content: center;
   
}
.card{
    background-color:white;
    width:80%;
    padding:50px;
    border:5px solid rgb(166, 166, 252);
    border-radius:1.5rem;
}

.errormessage{
    color:red;
}
.loginbutton{
    width:70px;
    height:40px;
    margin-top:50px;
     margin-left:35px;  
     background-color: rgb(19, 61, 247); 
     border-radius: 1rem;
    
}

```
### SCREENSHOT 1
![image](https://user-images.githubusercontent.com/104271789/191729600-0ed60f91-f14c-452a-9b6d-90d452c1e6f7.png)

### SCREENSHOT 2
![image](https://user-images.githubusercontent.com/104271789/191729336-16fff8df-8897-4c8b-8efa-48d123a4d832.png)

### SCREENSHOT 3
![image](https://user-images.githubusercontent.com/104271789/191729910-b729bafe-b381-4524-a60d-f169973bdd13.png)
