### DISCUSSION TITLE
Guided Exercise - React App with API Data Fetching - Magical Users

### DISCUSSION THREAD

**Discussion by akash-coded** [akash-coded/mern#170] [Tasks]
Let's create a React app called "Magical Users" that fetches user data from the ReqRes.in API, applies some magical transformations and validations to the data, and displays it in a fun and interactive way. This exercise will involve fetching data using Axios, manipulating and validating data using JavaScript, and creating unique and magical components. Here are the detailed step-by-step instructions:

Step 1: Setup
- Create a new directory for your project.
- Initialize a new React app using Create React App by running the command: `npx create-react-app magical-users`.
- Navigate into the project directory: `cd magical-users`.
- Start the development server: `npm start`.
- Open your browser and go to `http://localhost:3000` to see the default React app running.

Step 2: Install Axios
- Open your terminal and navigate to the project directory if you're not already there.
- Install Axios by running the command: `npm install axios`.

Step 3: Clear the default project
- Open the `src/App.js` file and remove the existing code.
- Replace it with the following code:
```jsx
import React, { useEffect, useState } from 'react';
import axios from 'axios';
import UserCard from './UserCard';

function App() {
  const [users, setUsers] = useState([]);

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    try {
      const response = await axios.get('https://reqres.in/api/users');
      setUsers(response.data.data);
    } catch (error) {
      console.log('Error fetching users:', error);
    }
  };

  return (
    <div>
      <h1>Magical Users</h1>
      <div className="user-container">
        {users.map(user => (
          <UserCard key={user.id} user={user} />
        ))}
      </div>
    </div>
  );
}

export default App;
```

Step 4: Create UserCard component
- Create a new file called `UserCard.js` in the `src` directory.
- Open `UserCard.js` and add the following code:
```jsx
import React, { useState, useEffect } from 'react';

function UserCard({ user }) {
  const [fullName, setFullName] = useState('');
  const [email, setEmail] = useState('');
  const [showMagic, setShowMagic] = useState(false);

  useEffect(() => {
    applyMagic();
  }, []);

  const applyMagic = () => {
    const nameParts = user.first_name.split('');
    const reversedName = nameParts.reverse().join('');
    const reversedEmail = user.email.split('').reverse().join('');
    setFullName(`${reversedName} ${user.last_name}`);
    setEmail(reversedEmail);
    setShowMagic(true);
  };

  const toggleMagic = () => {
    setShowMagic(!showMagic);
  };

  return (
    <div className="user-card">
      <h3>{fullName}</h3>
      <p>{email}</p>
      {showMagic && <p>🪄 Magic Applied!</p>}
      <button onClick={toggleMagic}>{showMagic ? 'Remove Magic' : 'Apply Magic'}</button>
    </div>
  );
}

export default UserCard;
```

Step 5: Add some styles
- Open the `src/App.css` file and replace the existing styles with the following code:
```css
body {
  font-family: Arial, sans-serif;
  text-align: center;
}

h1 {
  color: #333;
}

.user-container {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}

.user-card {
  width: 300px;
  margin: 1rem;
  padding: 1rem;
  background-color: #f7f7f7;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  transition: transform 0.3s;
}

.user-card:hover {
  transform: scale(1.05);
}

h3 {
  color: #333;
}

p {
  margin-top: 0.5rem;
  color: #666;
}

button {
  margin-top: 1rem;
  padding: 0.5rem 1rem;
  background-color: #333;
  color: #fff;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

button:hover {
  background-color: #666;
}
```

Step 6: Run the app
- Make sure the development server is running (`npm start`).
- Open your browser and go to `http://localhost:3000`.
- You should see the "Magical Users" heading and user cards fetched from the ReqRes.in API.
- Click on the "Apply Magic" button of any user card to see the magical transformations.
- Click on the "Remove Magic" button to revert the transformations.

Congratulations! You have created the "Magical Users" React app. It fetches user data from the ReqRes.in API, applies magical transformations and validations, and displays the transformed data in interactive user cards. Feel free to enhance the app by adding more magical transformations or creating additional unique and fun components. Let your imagination run wild and make the app truly magical!
