### DISCUSSION TITLE
Guided Assignment - React App with API Data Fetching - Enhanced Magical Users

### DISCUSSION THREAD

**Discussion by akash-coded** [akash-coded/mern#171] [Tasks]
Refer to previous task #170 

Let's enhance the "Magical Users" app to make it more fun and interactive. We'll introduce more components, compound workflows, and magical features. Here are the updated step-by-step instructions:

Step 1: Setup
- Ensure you have completed the previous setup steps.
- Make sure you have the `axios` library installed.

Step 2: Clear the default project
- Open the `src/App.js` file and remove the existing code.
- Replace it with the following code:
```jsx
import React, { useEffect, useState } from 'react';
import axios from 'axios';
import UserCard from './UserCard';
import MagicWand from './MagicWand';

function App() {
  const [users, setUsers] = useState([]);

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    try {
      const response = await axios.get('https://reqres.in/api/users');
      setUsers(response.data.data);
    } catch (error) {
      console.log('Error fetching users:', error);
    }
  };

  return (
    <div>
      <h1>Magical Users</h1>
      <div className="user-container">
        {users.map(user => (
          <UserCard key={user.id} user={user} />
        ))}
      </div>
      <MagicWand />
    </div>
  );
}

export default App;
```

Step 3: Create MagicWand component
- Create a new file called `MagicWand.js` in the `src` directory.
- Open `MagicWand.js` and add the following code:
```jsx
import React, { useState } from 'react';

function MagicWand() {
  const [showWand, setShowWand] = useState(false);

  const toggleWand = () => {
    setShowWand(!showWand);
  };

  return (
    <div>
      <button className="wand-button" onClick={toggleWand}>
        {showWand ? 'Hide Wand ✨' : 'Show Wand ✨'}
      </button>
      {showWand && (
        <div className="wand">
          <h2>Magic Wand</h2>
          <p>Point the wand to unleash magical powers!</p>
        </div>
      )}
    </div>
  );
}

export default MagicWand;
```

Step 4: Update UserCard component
- Open the `src/UserCard.js` file.
- Replace the `UserCard` component code with the following code:
```jsx
import React, { useState, useEffect } from 'react';

function UserCard({ user }) {
  const [fullName, setFullName] = useState('');
  const [email, setEmail] = useState('');
  const [showMagic, setShowMagic] = useState(false);

  useEffect(() => {
    applyMagic();
  }, []);

  const applyMagic = () => {
    const nameParts = user.first_name.split('');
    const reversedName = nameParts.reverse().join('');
    const reversedEmail = user.email.split('').reverse().join('');
    setFullName(`${reversedName} ${user.last_name}`);
    setEmail(reversedEmail);
    setShowMagic(true);
  };

  const toggleMagic = () => {
    setShowMagic(!showMagic);
  };

  return (
    <div className={`user-card ${showMagic ? 'magical' : ''}`}>
      <h3>{fullName}</h3>
      <p>{email}</p>
      {showMagic && <p className="magic-text">🪄 Magic Applied!</p>}
      <button className="magic-button" onClick={toggleMagic}>
        {showMagic ? 'Remove Magic' : 'Apply Magic'}
      </button>
    </div>
  );
}

export default UserCard;
```

Step 5: Update styles
- Open the `src/App.css` file.
- Replace the existing styles with the following code:
```css
body {
  font-family: Arial, sans-serif;
  text-align: center;
}

h1 {
  color: #333;
}

.user-container {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}

.user-card {
  width: 300px;
  margin: 1rem;
  padding: 1rem;
  background-color: #f7f7f7;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  transition: transform 0.3s;
}

.user-card.magical {
  border: 4px solid #ff9800;
}

.user-card:hover {
  transform: scale(1.05);
}

h3 {
  color: #333;
}

p {
  margin-top: 0.5rem;
  color: #666;
}

.magic-text {
  margin-top: 1rem;
  color: #ff9800;
}

.magic-button {
  margin-top: 1rem;
  padding: 0.5rem 1rem;
  background-color: #333;
  color: #fff;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.magic-button:hover {
  background-color: #666;
}

.wand-button {
  margin-top: 2rem;
  padding: 0.5rem 1rem;
  background-color: #333;
  color: #fff;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

.wand-button:hover {
  background-color: #666;
}

.wand {
  margin-top: 2rem;
  padding: 1rem;
  background-color: #f7f7f7;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.wand h2 {
  color: #333;
}

.wand p {
  margin-top: 0.5rem;
  color: #666;
}
```

Step 6: Run the app
- Make sure the development server is running (`npm start`).
- Open your browser and go to `http://localhost:3000`.
- You should see the "Magical Users" heading, user cards, and the magic wand button.
- Click on the "Apply Magic" button of any user card to see the magical transformations.
- Click on the "Remove Magic" button to revert the transformations.
- Click on the "Show Wand" button to reveal the magic wand.
- Toggle the wand to unleash magical powers!

Congratulations! You have enhanced the "Magical Users" React app to be more fun and interactive. Users can now apply and remove magical transformations to the user cards, as well as reveal and hide a magic wand. Feel free to add more magical features, components, or workflows to make the app even more enchanting. Let your creativity soar and have fun with your magical React app!
