### DISCUSSION TITLE
Surprise Test Exercise - Front-end - HTML + CSS - Building a Product Feedback Page for an E-commerce Website

### DISCUSSION THREAD

**Discussion by akash-coded** [akash-coded/mern#237] [Tasks]
This is a semi-guided, comprehensive exercise where candidates solve a real-world business problem using HTML and CSS. This exercise will incorporate HTML forms, semantic tags, lists, CSS selectors, and box model elements.

#### Business Problem Scenario
You are tasked with creating a product feedback page for "ShopEase," an e-commerce website. The page should allow users to submit feedback on products they've purchased. It needs to be user-friendly, visually appealing, and must follow good HTML and CSS practices.

#### Expected Output and Outcomes
- A web page with a form for submitting product feedback.
- Use of semantic HTML tags for structuring the page.
- Effective application of CSS for styling the page and form elements.
- The form should include multiple types of input fields and be intuitively laid out.

#### Page Structure and Content
1. **Header (`<header>`):** Should contain the company's logo (use placeholder text) and a navigation bar.
2. **Main Content (`<main>`):** 
   - A brief introduction to the feedback form.
   - The feedback form itself.
3. **Footer (`<footer>`):** Should contain copyright information and social media links (use placeholder text or icons).

#### Form Requirements
1. **Product Selection:** A dropdown list to select a product for feedback.
2. **Rating System:** Radio buttons for rating the product (1 to 5).
3. **Feedback Text Area:** A large text area for detailed feedback.
4. **Submit Button:** To submit the form.

#### Detailed Code Hints and Snippets

1. **Header with Navigation:**
   ```html
   <header>
       <h1>ShopEase</h1>
       <nav>
           <ul>
               <li><a href="#">Home</a></li>
               <!-- Add more list items for navigation links -->
           </ul>
       </nav>
   </header>
   ```

2. **Main Content with Form:**
   ```html
   <main>
       <h2>Product Feedback</h2>
       <form>
           <label for="product-select">Choose a product:</label>
           <select id="product-select" name="product">
               <option value="">--Please choose an option--</option>
               <option value="product1">Product 1</option>
               <!-- Add options for more products -->
           </select>

           <p>Please rate the product:</p>
           <label>
               <input type="radio" name="rating" value="1"> 1
           </label>
           <!-- Add radio buttons for ratings 2 to 5 -->

           <label for="feedback">Your feedback:</label>
           <textarea id="feedback" name="feedback" rows="4" cols="50"></textarea>

           <input type="submit" value="Submit">
       </form>
   </main>
   ```

3. **Footer:**
   ```html
   <footer>
       <p>© 2023 ShopEase, Inc.</p>
       <!-- Add placeholder or icons for social media links -->
   </footer>
   ```

4. **CSS Styling:**
   ```css
   body {
       font-family: Arial, sans-serif;
       margin: 0;
       padding: 0;
       background-color: #f4f4f4;
   }
   header, footer {
       background-color: ____________; /* Fill with a color */
       color: ____________; /* Fill with a contrasting color */
       padding: 10px;
   }
   main {
       padding: 20px;
   }
   form {
       background-color: white;
       border: 1px solid #ddd;
       padding: 20px;
       margin-top: 20px;
   }
   label {
       display: block;
       margin-top: 10px;
   }
   input[type="submit"] {
       background-color: ____________; /* Fill with a color */
       color: white;
       padding: 10px 15px;
       border: none;
       cursor: pointer;
   }
   input[type="submit"]:hover {
       background-color: ____________; /* Fill with a darker shade */
   }
   ```

#### Test Guidelines
- Candidates should fill in the blanks and add necessary HTML and CSS to complete the page.
- The page should be responsive and follow the basic principles of web design.
- The form should be properly formatted and should include all the required fields.

#### Evaluation Criteria
- Correct use of HTML semantic tags.
- Effective application of CSS box model properties.
- Visual appeal and usability of the form.
- Adherence to the provided specifications and creativity in design.

This test exercise provides a comprehensive challenge that encompasses essential HTML and CSS skills, giving candidates an opportunity to demonstrate their understanding and creativity in solving a real-world problem.

**Comment by akash-coded** [comment]
Let's focus on the fundamentals of HTML and CSS basics, such as color, font, and other basic properties, along with essential CSS selectors. The revised surprise test exercise will emphasize these core concepts.

### Surprise Test Exercise - 2: Styling a Basic Blog Page [EXTRA - Additional for Bonus Marks]

#### Objective
Create and style a simple blog page focusing on the use of fundamental HTML and CSS properties. The page will include a header, a main content area with a blog post, and a footer.

#### Expected Output and Outcomes
- A neatly structured HTML page using semantic tags.
- Effective use of basic CSS properties like color, font, margin, padding, and border.
- Application of CSS selectors to style different elements of the page.

#### Scenario and Functionality
The blog page should include:
- A header with the blog's title.
- A main section with a blog post, including a title, date, text, and an image.
- A footer with copyright information.

#### Page Structure and Content

**HTML:**
1. **Header:**
   ```html
   <header>
       <h1>My Simple Blog</h1>
   </header>
   ```

2. **Main Content:**
   ```html
   <main>
       <article>
           <h2>Blog Post Title</h2>
           <p class="date">Posted on January 1, 2023</p>
           <p>Lorem ipsum dolor sit amet...</p>
           <!-- Add an image with alt text -->
           <img src="path-to-image.jpg" alt="Descriptive Alt Text">
       </article>
   </main>
   ```

3. **Footer:**
   ```html
   <footer>
       <p>© 2023 My Simple Blog</p>
   </footer>
   ```

**CSS:**

4. **Basic Styling:**
   - Style the `<body>` to set a font and a background color.
   - Style the `<header>` to make it visually distinct.
   - Style the `<footer>` similarly to the header but with different colors.

   **Code Hints:**
   ```css
   body {
       font-family: Arial, sans-serif;
       background-color: #f0f0f0;
   }
   header {
       background-color: #333;
       color: #fff;
       text-align: center;
       padding: 10px 0;
   }
   footer {
       background-color: #222;
       color: #ccc;
       text-align: center;
       padding: 5px 0;
   }
   ```

5. **Styling Main Content:**
   - Apply margins and padding to the `<article>` tag to ensure the text doesn’t touch the edges of the browser window.
   - Style the blog post title (`<h2>`) and date (`<p class="date">`) to differentiate them from the main text.

   **Code Hints:**
   ```css
   article {
       margin: 20px;
       padding: 15px;
       background-color: white;
       border: 1px solid #ddd;
   }
   .date {
       color: #666;
       font-style: italic;
   }
   ```

6. **Image Styling:**
   - Ensure the image in the article is responsive and does not overflow the container.
   
   **Code Hints:**
   ```css
   img {
       max-width: 100%;
       height: auto;
       display: block;
       margin: 0 auto;
   }
   ```

#### Task: Completing the Blog Page
Candidates are required to:
- Fill in the necessary HTML structure as per the provided snippets.
- Apply CSS to style each section of the page, ensuring a harmonious and readable layout.
- Use fundamental CSS properties and selectors to achieve the desired appearance.

#### Evaluation Criteria
- Correct usage and structuring of HTML elements.
- Effective application of CSS properties for layout and styling.
- Visual appeal and readability of the final page.

This exercise tests the candidates' understanding of basic HTML and CSS concepts in a practical scenario, reinforcing fundamental web development skills. It provides a platform to showcase their ability to create a simple yet effective webpage.
